openapi: '3.0.2'
info:
  title: Geotag Mobile Apps API Documentations
  description: this API just a references how the system on our apps is work, there might be some different Responses between the docs and Apps
  version: 'BETA'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      tags:
        - Authentication System
      summary: Sign-In to the Mobile Apps
      operationId: Sign In
      requestBody:
        description: Login based on User Role
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/xml:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: OK, set cookies with user data
        '401':
          description: Authentication failed

  /auth/register:
    post:
      tags:
        - Authentication System
      summary: Register a new user for Mobile User
      operationId: Register Mobile
      requestBody:
        description: Create a new user account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/xml:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      responses:
        '200':
          description: Created, redirected to login.
        '400':
          description: User registration failed
        '409':
          description: User already exists
        '500':
          description: Internal Server Error

  /user/edit:
    post:
      tags:
        - User Profiles
      summary: Edit Information about User Authentication
      operationId: EditUser
      requestBody:
        description: Edit Existing User, image must be posted using html forms.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Edit User'
          application/xml:
            schema:
              $ref: '#/components/schemas/Edit User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Edit User'
        required: true
      responses:
        '200':
          description: Edited Succesfully
        '413':
          description: Payload Too Large
        '500':
          description: Internal Server Error

  /user/reset:
    post:
      tags:
        - User Profiles
      summary: Reset User Password with generated links
      operationId: reserUser
      requestBody:
        description: Edit Existing User, image must be posted using html forms.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reset Password'
          application/xml:
            schema:
              $ref: '#/components/schemas/Reset Password'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reset Password'
        required: true
      responses:
        '200':
          description: Reset Succesfully
        '500':
          description: Internal Server Error



components:
  schemas:
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minimum: 6
          format: password

    Register:
      type: object
      required:
        - firstname
        - lastname
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minimum: 6
          format: password
        firstname:
          type: string
          format: string
        lastname:
          type: string
          format: string

    Edit User:
      type: object
      required:
        - uid
        - email
        - displayName
        - image
      properties:
        uid:
          type: string
          format: uuid
        email: 
          type: string
          format: email
        displayName:
          type: string
          format: string
        image:
          type: string
          format: binary

    Reset Password:
      type: object
      required: 
        - email
      properties:
        email:
          type: string
          format: string
