export enum StorageContentType {
  JPEG = 'image/jpeg',
  PNG = 'image/png',
  GIF = 'image/gif',
  BMP = 'image/bmp',
  SVG = 'image/svg+xml',
  MP4 = 'video/mp4',
  WebM = 'video/webm',
  OggVideo = 'video/ogg',
  MP3 = 'audio/mpeg',
  OggAudio = 'audio/ogg',
  WAV = 'audio/wav',
  PDF = 'application/pdf',
  Word = 'application/msword',
  Excel = 'application/vnd.ms-excel',
  PowerPoint = 'application/vnd.ms-powerpoint',
  PlainText = 'text/plain',
  HTML = 'text/html',
  CSS = 'text/css',
  JavaScript = 'application/javascript',
  ZIP = 'application/zip',
  TAR = 'application/x-tar',
}
